# Generated by Django 2.0.13 on 2020-08-07 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.FileField(upload_to='')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30, unique=True)),
                ('group_code', models.CharField(max_length=30, unique=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_group_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(choices=[('g', 'invite'), ('u', 'request'), ('a', 'accepted'), ('r', 'refused'), ('b', 'block')], max_length=10)),
                ('bio', models.TextField(blank=True, default='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(related_name='member_group_set', through='community.Profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feed',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Group'),
        ),
        migrations.AddField(
            model_name='feed',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Profile'),
        ),
    ]
