# Generated by Django 2.0.13 on 2020-08-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
