# Generated by Django 2.0.13 on 2020-08-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200810_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
